# BSD 3-Clause All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

{{ if .Values.volumes.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: irods-test-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - ReadWriteOnce
  {{ if .Values.isAWS }}
  storageClassName: {{ .Values.volumes.storageClass }}
  {{ end }}
  resources:
    requests:
      storage: {{ .Values.volumes.size }}
{{ end }}