apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "irods-service.fullname" . }}
  labels:
    {{- include "irods-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "irods-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "irods-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.podSecurityContext }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.initContainer }}
      initContainers:
        - name: load-test-env
          image: alpine/git
          command: ["/bin/sh", "-c"]
          args:
            - git clone --single-branch -- https://github.com/irods/irods_testing_environment.git {{ .Values.storage.testing.mountPath }}/tests;
              git clone --single-branch -- https://github.com/irods/irods.git {{ .Values.storage.testing.mountPath }}/runtime;
          volumeMounts:
          - name: {{ .Values.storage.testing.name }}
            mountPath: {{ .Values.storage.testing.mountPath }}
      {{- end }}
      containers:
        - name: {{ include "irods-service.fullname" . }}
          command: [ '/bin/sh' , '-c']
          {{- if .Values.serverInit.isProvider }}
          args: [ '{{ .Values.serverInit.initScriptMountPath }} && until false; do sleep 2147483647d; done;' ]
          {{- else }}
          args: ['until false; do sleep 2147483647d; done;']
          {{- end }}

          {{- if .Values.securityContext}}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          {{- end }}
          image: "{{ .Values.image.repository}}{{ .Values.image.os }}-{{ .Values.image.os_version }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- if .Values.service }}
          ports:
            - name: primary-port
              containerPort: {{ .Values.service.primaryPort }}
              protocol: TCP
            - name: secondary-port
              containerPort: {{ .Values.service.secondaryPort }}
              protocol: TCP
            {{- range untilStep (int .Values.service.minPort) (int .Values.service.maxPort) 1 }}
            - name: svc-port-{{ . }}
              containerPort: {{ . }}
              protocol: TCP
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
          {{- if .Values.serverInit.isProvider }}
          - name: init-irods-script
            mountPath: {{ .Values.serverInit.initScriptMountPath }}
            subPath: {{ .Values.serverInit.initScriptName | quote }}
          - name: init-service-script
            mountPath: {{ .Values.serverInit.serviceInitMountPath }}
            subPath: {{ .Values.serverInit.serviceInitName | quote }}
          {{- end }}
          {{- if .Values.storage.testing }}
          - name: {{ .Values.storage.testing.name }}
            mountPath: {{ .Values.storage.testing.mountPath }}
          {{- end }}
          {{- if .Values.storage.vault }}
          - name: {{ .Values.storage.vault.name }}
            mountPath: {{ .Values.storage.vault.mountPath }}
          {{- end }}
          {{- if .Values.storage.zone }}
          - name: {{ .Values.storage.zone.name }}
            mountPath: {{ .Values.storage.zone.mountPath }}
          {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.serverInit.isProvider }}
        - name: init-irods-script
          configMap:
            name: "{{- include "irods-service.fullname" . }}-scripts"
            defaultMode: 0777
        - name: init-service-script
          configMap:
            name: "{{- include "irods-service.fullname" . }}-scripts"
            defaultMode: 0777
      {{- end }}
      {{- if .Values.storage.testing }}
        - name: {{ .Values.storage.testing.name }}
          persistentVolumeClaim:
            claimName: {{ include "irods-service.fullname" . }}-testing-pvc
      {{- end }}
      {{- if .Values.storage.vault }}
        - name: {{ .Values.storage.vault.name }}
          persistentVolumeClaim:
            claimName: {{ include "irods-service.fullname" . }}-vault-pvc
      {{- end }}
      {{- if .Values.storage.zone }}
        - name: {{ .Values.storage.zone.name }}
          persistentVolumeClaim:
            claimName: {{ include "irods-service.fullname" . }}-zone-pvc
      {{- end }}