apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: n4bi-irods-gateway
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 1247
        name: tcp
        protocol: TCP
      hosts:
        # hosts are restricted and need to be apply for in the project application.
        # hosts has to be prefixed with namespace/
        - "n4bi-irods/n4bi-irods.uni-muenster.de"
