# SPDX-FileCopyrightText: 2024 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

{{ if .Values.storage.opt }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "irods-service.fullname" . }}-opt-pvc
spec:
  accessModes:
  - {{ .Values.storage.opt.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.opt.size }}
{{ end }}
{{ if .Values.storage.var }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "irods-service.fullname" . }}-var-pvc
spec:
  accessModes:
  - {{ .Values.storage.var.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.var.size }}
{{ end }}
{{ if .Values.storage.zone }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "irods-service.fullname" . }}-zone-pvc
spec:
  accessModes:
  - {{ .Values.storage.zone.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.zone.size }}
{{ end }}
