{{ if .Values.storage.testing }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "irods-service.fullname" . }}-testing-pvc
spec:
  accessModes:
  - {{ .Values.storage.testing.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.testing.size }}
{{ end }}
{{ if .Values.storage.var }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "irods-service.fullname" . }}-var-pvc
spec:
  accessModes:
  - {{ .Values.storage.var.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.var.size }}
{{ end }}
{{ if .Values.storage.zone }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "irods-service.fullname" . }}-zone-pvc
spec:
  accessModes:
  - {{ .Values.storage.zone.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.zone.size }}
{{ end }}
