# BSD 3-Clause All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

{{ if .Values.storage.opt }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "irods-service.fullname" . }}-opt-pvc
spec:
  accessModes:
  - {{ .Values.storage.opt.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.opt.size }}
  storageClassName: {{ .Values.storage.opt.storageClass }}
{{ end }}
{{ if .Values.storage.var }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "irods-service.fullname" . }}-var-pvc
spec:
  accessModes:
  - {{ .Values.storage.var.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.var.size }}
  storageClassName: {{ .Values.storage.var.storageClass }}
{{ end }}
{{ if .Values.storage.zone }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "irods-service.fullname" . }}-zone-pvc
spec:
  accessModes:
  - {{ .Values.storage.zone.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.zone.size }}
  storageClassName: {{ .Values.storage.zone.storageClass }}
{{ end }}
