# BSD 3-Clause All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

{{- if .Values.service }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "irods-service.fullname" . }}
  labels:
    {{- include "irods-service.labels" . | nindent 4 }}
  annotations:
    networking.istio.io/exportTo: istio-ingressgateway
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: tcp-pri-port
      port: {{ .Values.service.primaryPort }}
      targetPort: {{ .Values.service.primaryPort }}
      protocol: TCP
    - name: tcp-sec-port
      port: {{ .Values.service.secondaryPort }}
      targetPort: {{ .Values.service.secondaryPort }}
      protocol: TCP
    {{- range untilStep (int .Values.service.minPort) (int .Values.service.maxPort) 1 }}
    - name: tcp-s-prt-{{ . }}
      port: {{ . }}
      targetPort: {{ . }}
      protocol: TCP
    {{- end }}
  selector:
    {{- include "irods-service.selectorLabels" . | nindent 4 }}
{{- end }}
