# BSD 3-Clause All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

apiVersion: v1
kind: Service
metadata:
  name: {{ include "irods-supervisor-db.fullname" . }}
  labels:
    {{- include "irods-supervisor-db.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}
  selector:
    {{- include "irods-supervisor-db.selectorLabels" . | nindent 4 }}
