# BSD 3-Clause All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

---
{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "irods-rabbitmq.serviceAccountName" . }}
  labels:
    {{- include "irods-rabbitmq.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
