# SPDX-FileCopyrightText: 2022 Renaissance Computing Institute. All rights reserved.
# SPDX-FileCopyrightText: 2023 Renaissance Computing Institute. All rights reserved.
#
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-License-Identifier: LicenseRef-RENCI
# SPDX-License-Identifier: MIT

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: irods-test-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - {{ .Values.volumes.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volumes.size }}

