# BSD 3-Clause License All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause License

{{ if .Values.volumes.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: irods-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - {{ .Values.volumes.accessMode }}
  resources:
    requests:
      storage: {{ .Values.volumes.size }}
{{ end }}
