{{ if .Values.backup.enable }}
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "irods-postgres.fullname" . }}-backup-job
  labels:
    {{- include "irods-postgres.labels" . | nindent 4 }}
spec:
  schedule: "{{ .Values.backup.crontab }}"
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3
      template:
        spec:
          containers:
          - name: {{ .Chart.Name }}-backup-job
            image: "{{ .Values.backupImage.repository }}:{{ .Values.backupImage.tag }}"
            imagePullPolicy: {{ .Values.backupImage.pullPolicy }}
            volumeMounts:
            - name:  {{ .Values.volumes.name }}
              mountPath: "/data"
            - mountPath: dumpDatabase.sh
              name: "backup-script"
              subPath: "dumpDatabase.sh"
            command: ['bash', './dumpDatabase.sh']
            env:
            - name: LOG_PATH
              value: "/data/logs"
            - name: IRODS_DB_HOST
              value: {{ include "irods-postgres.fullname" . | quote }}
            - name: IRODS_DB_PORT
              value: "5432"
            - name: PGUSER
              value: {{ .Values.adminUser | quote }}
            - name: PGPASSWORD
              value: {{ .Values.adminPassword | quote }}
          restartPolicy: Never
          volumes:
            - name: {{ .Values.volumes.name }}
              persistentVolumeClaim:
                claimName: {{ .Values.volumes.claimName }}
            - name: backup-script
              configMap:
                name: "{{- include "irods-postgres.fullname" . }}-scripts"
                defaultMode: 0777
          securityContext:
            {{- toYaml .Values.backupSecurityContext | nindent 12 }}
  {{ end }}