---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "irods-postgres.fullname" . }}
  labels:
    {{- include "irods-postgres.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: {{ .Values.service.name }}
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: {{ .Values.service.protocol }}

  selector:
    {{- include "irods-postgres.selectorLabels" . | nindent 4 }}
