# BSD 3-Clause All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

# Default values for irods-supervisor-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccount: {}
podAnnotations: {}
nodeSelector: {}
tolerations: []
affinity: {}

storage:
  create: true
  name: irods-postgres-db-vol
  size: 1Gi
  accessMode: "ReadWriteMany"
  dataMountPath: /var/lib/postgresql/data

podSecurityContext:
  fsGroup: 999

securityContext:
  runAsUser: 999
  runAsNonRoot: true

service:
  name: service-port
  type: ClusterIP
  protocol: TCP
  port: 5432

resources:
   limits:
     cpu: 150m
     memory: 150Mi
   requests:
     cpu: 100m
     memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

initDB:
  superv: true
  user: "superv"
  password: "somepassword"

envParams:
  param1:
    envParamName: "POSTGRES_USER"
    envParamValue: "postgres"
  param2:
    envParamName: "POSTGRES_PASSWORD"
    envParamValue: "somepassword"
  param3:
    envParamName: "PGDATA"
    envParamValue: "/var/lib/postgresql/data/db_data"

dataVolumes:
  name: data-vol
  claimName: some-pvc

backupImage:
  repository: containers.renci.org/irods/db-backup-job
  tag: "latest"
  pullPolicy: Always

backup:
  enable: false
  restoreDB: false
  crontab: "0 5 * * *"
