# BSD 3-Clause All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

# Default values for irods-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: some-repo
  pullPolicy: IfNotPresent
  tag: "0.0.0"

imagePullSecrets: []
nameOverride: "test"
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: false
  annotations: {}
  name:

storage:
  name: db-vol
  create: false
  size: 1Mi
  accessMode: "ReadWriteOnce"
  dataMountPath: /somedir

service:
  name: service-port-name
  type: ClusterIP
  protocol: TCP
  port: 1234

resources:
   limits:
     ephemeral-storage:
     cpu: 150m
     memory: 150Mi
   requests:
     cpu: 100m
     memory: 64Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

initDB:
  mysql: false
  postgres: false
  user: "someuser"
  password: "tsomepassword"
  initScript: "init.sh"

backup:
  enable: false
  restoreDB: false
  crontab: "0 5 * * *"
