# BSD 3-Clause All rights reserved.
#
# SPDX-License-Identifier: BSD 3-Clause

# Default values for irods-db.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: some-repo
  pullPolicy: IfNotPresent
  tag: "0.0.0"

imagePullSecrets: []
nameOverride: "test"
fullnameOverride: ""
podAnnotations: {}
podSecurityContext: {}
securityContext: {}
nodeSelector: {}
tolerations: []
affinity: {}
serviceAccount:
  create: false
  annotations: {}
  name:

storage:
  name: db-vol
  create: true
  size: 1Gi
  accessMode: "ReadWriteMany"
  dataMountPath: /var/lib/postgresql/data
  # mysql data mount path
  #   dataMountPath: /var/lib/mysql

service:
  name: service-port
  type: ClusterIP
  protocol: TCP
  port: 5432

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

irodsInitDB:
  irods_mysql: false
  irods_postgres: true
  user: "irods"
  password: "testpassword"
  initScript: "init-irods-pg-db.sh"

# postgres env params
envParams:
  param1:
    envParamName: "POSTGRES_USER"
    envParamValue: "postgres"
  param2:
    envParamName: "POSTGRES_PASSWORD"
    envParamValue: "testpassword"
  param3:
    envParamName: "PGDATA"
    envParamValue: "/var/lib/postgresql/data/db_data"

# mysql env params
#envParams:
#  param1:
#    envParamName: "MYSQL_USER"
#    envParamValue: "irods"
#  param2:
#    envParamName: "MYSQL_ROOT_PASSWORD"
#    envParamValue: "testpassword"
#  param3:
#    envParamName: "MYSQL_PASSWORD"
#    envParamValue: "testpassword"

dataVolumes:
  name: data-vol
  claimName: irods-pvc
