{{ if .Values.storage.create }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "irods-mysql.fullname" . }}-pvc
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
  - {{ .Values.storage.accessMode }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
{{ end }}
