apiVersion: v1
kind: Secret
metadata:
  name: irods-job-account-token
  namespace: irods-dev
  annotations:
    kubernetes.io/service-account.name: irods-job-account
type: kubernetes.io/service-account-token
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: irods-job-account
  namespace: irods-dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: irods-job-account-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - create
  - delete
- apiGroups:
  - 'batch'
  resources:
    - jobs
  verbs:
    - list
    - create
    - delete
- apiGroups:
  - ""
  resources:
    - services
  verbs:
    - list
    - create
    - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: irods-job-account-rolebinding
roleRef:
  kind: Role
  name: irods-job-account-role
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: irods-job-account
---
